# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
crossoverC <- function(parent1, parent2) {
    .Call('PESAII_crossoverC', PACKAGE = 'PESAII', parent1, parent2)
}

#' @export
dominatesC <- function(x, y) {
    .Call('PESAII_dominatesC', PACKAGE = 'PESAII', x, y)
}

nonDominatedSolutionsCimp <- function(m) {
    .Call('PESAII_nonDominatedSolutionsCimp', PACKAGE = 'PESAII', m)
}

#'@export
isNonDominated <- function(ep, sol) {
    .Call('PESAII_isNonDominated', PACKAGE = 'PESAII', ep, sol)
}

minVector <- function(x, y) {
    .Call('PESAII_minVector', PACKAGE = 'PESAII', x, y)
}

applySelectionToNeighbours <- function(x, y) {
    .Call('PESAII_applySelectionToNeighbours', PACKAGE = 'PESAII', x, y)
}

mutateCR <- function(sol, nn, L, neighborhood, randomVectorMutation, randomVectorSelection) {
    .Call('PESAII_mutateCR', PACKAGE = 'PESAII', sol, nn, L, neighborhood, randomVectorMutation, randomVectorSelection)
}

#'@export
getAssignmentC <- function(grid, nGrid, matEP) {
    .Call('PESAII_getAssignmentC', PACKAGE = 'PESAII', grid, nGrid, matEP)
}

